version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "dependabot hex"
    labels:
      - "dependencies"
    reviewers:
      - "dustessavdh"
    assignees:
      - "dustessavdh"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/assets"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "dependabot npm"
    labels:
      - "dependencies"
    reviewers:
      - "dustessavdh"
    assignees:
      - "dustessavdh"
    open-pull-requests-limit: 0

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "dependabot"
    labels:
      - "dependencies"
    reviewers:
      - "dustessavdh"
    assignees:
      - "dustessavdh"
    open-pull-requests-limit: 0
