version: "3.8"

services:
  site:
    container_name: site
    build: .
    ports:
      - 4000:4000
    depends_on:
      - db
    volumes:
      - type: bind
        source: .
        target: /app
      - site_build:/app/_build
    command: bash bin/run_dev

  db:
    container_name: db
    build:
      context: .
      dockerfile: postgres.Dockerfile
    ports:
      - 5432:5433
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  site_build: null
  db_data: null
